
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: sys as sysdba
    password: 123456!!@@
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      auto-commit: false


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB